name: bootstrap tests
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with: 
          distribution: 'zulu'
          java-version: '21'
          check-latest: true
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.17.0
      - name: run tests
        run: mvn test  -Dtest=RegistrationPageTests -Dbrowser="chrome" -Dimplicit_time=4 -Dbrowser_maximized="true" -Dbrowser_headless="true" -Dbrowser_incognito="false"
      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v5.2.0
        if: success() || failure() 
        with:
          report_paths: 'target/surefire-reports/TEST-*.xml'
        

          
            
          
      
      
